apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-ticket-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-ticket
  template:
    metadata:
      labels:
        app: train-ticket
    spec:
      containers:
        - name: train-ticket-container
          image: indugone/train-ticket-app
          ports:
            - containerPort: 5000
---
# 🚂 Train Ticket Service
apiVersion: v1
kind: Service
metadata:
  name: train-ticket-service
spec:
  selector:
    app: train-ticket
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
 
